# backend/app/api/v1/endpoints/filaments.py
from typing import List, Optional
from fastapi import APIRouter, Depends, HTTPException
from sqlalchemy.orm import Session

from app.db.session import get_db
from app.schemas.filament import FilamentRead, FilamentEnrichment, UnlinkedMatchResponse
from app.crud import crud_filament
from app.models.base_models import FilamentSpool, FilamentStatus

router = APIRouter()

@router.get("/", response_model=List[FilamentRead])
def get_all_filaments(db: Session = Depends(get_db)):
    """
    Retrieve all filament spools.
    """
    return crud_filament.get_multi(db)

@router.put("/{filament_id}/enrich", response_model=FilamentRead)
def enrich_filament_data(filament_id: int, enrichment_data: FilamentEnrichment, db: Session = Depends(get_db)):
    """
    Enrich a 'DRAFT' filament spool with price and owner information.
    """
    db_filament = crud_filament.get(db, id=filament_id)
    if not db_filament:
        raise HTTPException(status_code=404, detail="Filament not found")

    # Here you would call a service function to apply the logic
    # For now, we call crud directly
    updated_filament = crud_filament.enrich(db=db, db_obj=db_filament, obj_in=enrichment_data)
    return updated_filament

@router.get("/unlinked-matches", response_model=List[UnlinkedMatchResponse])
def get_unlinked_matches(
    material_type: Optional[str] = None,
    color_hex: Optional[str] = None,
    owner_id: Optional[int] = None,
    spool_id: Optional[int] = None,
    db: Session = Depends(get_db)
):
    """
    Find matching unlinked delivered spools generated by delivered orders.
    """
    if spool_id is not None:
        db_spool = db.query(FilamentSpool).filter(FilamentSpool.id == spool_id).first()
        if not db_spool:
            raise HTTPException(status_code=404, detail="Spool not found")
        # Use values from the spool
        material_type = db_spool.material_type
        color_hex = db_spool.color_hex
        owner_id = db_spool.owner_id
    else:
        if not material_type or not color_hex:
            raise HTTPException(
                status_code=400,
                detail="Must provide spool_id or both material_type and color_hex"
            )

    # Query matching physical spools generated by delivered orders
    # status DRAFT, owner_id matched or None, order_item_id set, bambu_tray_id is null
    query = db.query(FilamentSpool).filter(
        FilamentSpool.status == FilamentStatus.DRAFT,
        FilamentSpool.bambu_tray_id == None,
        FilamentSpool.order_item_id != None,
        FilamentSpool.material_type == material_type,
        FilamentSpool.color_hex == color_hex
    )

    if owner_id is not None:
        query = query.filter(
            (FilamentSpool.owner_id == owner_id) | (FilamentSpool.owner_id == None)
        )
    else:
        query = query.filter(FilamentSpool.owner_id == None)

    spools = query.all()

    results = []
    for spool in spools:
        # Load order/item details if they exist
        order_id = None
        order_date = None
        owner_username = None
        sku = spool.sku

        if spool.order_item:
            sku = spool.sku or getattr(spool.order_item, "sku", None) or spool.order_item.product_name
            if spool.order_item.order:
                order_id = spool.order_item.order.id
                order_date = spool.order_item.order.order_date

        if spool.owner:
            owner_username = spool.owner.username

        results.append(
            UnlinkedMatchResponse(
                id=spool.id,
                material_type=spool.material_type,
                color_hex=spool.color_hex,
                remaining_weight_g=spool.remaining_weight_g,
                status=spool.status,
                price=spool.price,
                spool_type=spool.spool_type,
                owner_id=spool.owner_id,
                order_item_id=spool.order_item_id,
                location=spool.location,
                product_slug=spool.product_slug,
                sku=sku,
                variant_title=spool.variant_title,
                order_id=order_id,
                order_date=order_date,
                owner_username=owner_username,
            )
        )

    return results
